// <auto-generated />
namespace IdentityTutorial.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class removedrolesanduserroles : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(removedrolesanduserroles));
        
        string IMigrationMetadata.Id
        {
            get { return "201512151322022_removed roles and userroles"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
